In [2]:
import pandas as pd
from IPython.core.display import display

data = pd.Series(["Январь", "Февраль", "Март", "Апрель"],
                 index = ['Первый', "Второй", "Третий", "Четвёртый"])
display(data)

Первый        Январь
Второй       Февраль
Третий          Март
Четвёртый     Апрель
dtype: object

In [6]:
import pandas as pd

data = pd.Series(list(range(10, 1001)))
display(data)


print(data.loc[10] + data.loc[23] - data.loc[245] + data.iloc[122])

0        10
1        11
2        12
3        13
4        14
       ...
986     996
987     997
988     998
989     999
990    1000
Length: 991, dtype: int64

-70

In [17]:
import pandas as pd


football = pd.read_csv('./data_sf.xls')
display(football.info())
display(football['Club'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 42 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12897 non-null  int64
 1   Name             12897 non-null  object
 2   Age              12897 non-null  int64
 3   Nationality      12897 non-null  object
 4   Club             12897 non-null  object
 5   Value            12897 non-null  int64
 6   Wage             12897 non-null  int64
 7   Position         12897 non-null  object
 8   Crossing         12897 non-null  int64
 9   Finishing        12897 non-null  int64
 10  HeadingAccuracy  12897 non-null  int64
 11  ShortPassing     12897 non-null  int64
 12  Volleys          12897 non-null  int64
 13  Dribbling        12897 non-null  int64
 14  Curve            12897 non-null  int64
 15  FKAccuracy       12897 non-null  int64
 16  LongPassing      12897 non-null  int64
 17  BallControl      12897 non-null  int64
 18  Acceleration     12897 non-null  int64
 19  SprintSpeed      12897 non-null  int64
 20  Agility          12897 non-null  int64
 21  Reactions        12897 non-null  int64
 22  Balance          12897 non-null  int64
 23  ShotPower        12897 non-null  int64
 24  Jumping          12897 non-null  int64
 25  Stamina          12897 non-null  int64
 26  Strength         12897 non-null  int64
 27  LongShots        12897 non-null  int64
 28  Aggression       12897 non-null  int64
 29  Interceptions    12897 non-null  int64
 30  Positioning      12897 non-null  int64
 31  Vision           12897 non-null  int64
 32  Penalties        12897 non-null  int64
 33  Composure        12897 non-null  int64
 34  Marking          12897 non-null  int64
 35  StandingTackle   12897 non-null  int64
 36  SlidingTackle    12897 non-null  int64
 37  GKDiving         12897 non-null  int64
 38  GKHandling       12897 non-null  int64
 39  GKKicking        12897 non-null  int64
 40  GKPositioning    12897 non-null  int64
 41  GKReflexes       12897 non-null  int64
dtypes: int64(38), object(4)
memory usage: 4.1+ MB

None

0               FC Barcelona
1                   Juventus
2        Paris Saint-Germain
3          Manchester United
4            Manchester City
                ...
12892        Crewe Alexandra
12893         Trelleborgs FF
12894       Cambridge United
12895        Tranmere Rovers
12896        Tranmere Rovers
Name: Club, Length: 12897, dtype: object

In [92]:
import pandas as pd

football = pd.read_csv('./data_sf.xls')

# display(football.describe())

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(football.describe())

# football.info()
# display(football.describe(include = ['object']))


display(
    round(football.Age.describe()['mean']),
    football.Age.describe()['min'],
    football.Wage.describe()['max'],
    football.Wage.describe()['50%'],
    football.Penalties.describe()['min'],
    football.ShortPassing.describe()['25%'],

    football.Nationality.describe()['top'],
    football.Nationality.describe()['freq'],
    football.Club.describe()['unique'],
    football.describe(include = ['object'])['Position']['freq'],
    football.Age.describe()['max']
)

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,44.264403,40.321625,50.115143,55.463596,63.109715,63.205629,61.819648,59.430565,63.171978,52.530666,64.285415,61.123052,64.271614,43.971931,53.777933,44.875940,47.166008,50.843374,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,17.781283,16.718481,15.215160,16.692643,15.129988,14.903845,14.858729,8.875832,14.190700,16.975214,11.765467,16.194498,12.550696,18.769749,17.232716,20.188799,19.245882,13.745960,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,6.000000,3.000000,9.000000,5.000000,12.000000,12.000000,15.000000,21.000000,16.000000,2.000000,15.000000,12.000000,17.000000,3.000000,11.000000,3.000000,2.000000,10.000000,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,32.000000,29.000000,40.000000,51.000000,55.000000,55.000000,53.000000,54.000000,55.000000,42.000000,57.000000,54.000000,57.000000,29.000000,41.000000,24.000000,35.000000,42.000000,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,45.000000,39.000000,53.000000,60.000000,66.000000,66.000000,64.000000,59.000000,65.000000,56.000000,65.000000,64.000000,65.000000,47.000000,56.000000,51.000000,52.000000,52.000000,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,58.000000,52.000000,61.000000,65.000000,74.000000,73.000000,72.000000,65.000000,73.000000,65.000000,72.000000,72.000000,73.000000,59.000000,67.000000,62.000000,61.000000,60.000000,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,93.000000,94.000000,93.000000,96.000000,97.000000,96.000000,96.000000,96.000000,96.000000,95.000000,95.000000,96.000000,97.000000,94.000000,95.000000,92.000000,95.000000,94.000000,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

25

16.0

565000.0

2000.0

5.0

50.0

'England'

1368

650

1641

45.0

In [101]:
import pandas as pd

football = pd.read_csv('./data_sf.xls')

display(
    round(football.Age.mean()),
    football.Composure.count(),
    round(football.ShortPassing.std(), 2),
    football.Wage.sum(),
    football.Value.min(),
)

25

12897

14.74

96954000

0

In [107]:
import pandas as pd
football = pd.read_csv('./data_sf.xls')

display(
    football[football.Age > football.Age.mean()],

    football[(football.Age < football.Age.mean())|
        (football.Club == 'FC Barcelona')],

)

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12746,12975,Teng Shangkun,27,China PR,Tianjin TEDA FC,20000,1000,GK,10,8,...,17,58,28,10,13,46,56,55,45,53
12749,12978,M. Mansour,26,Saudi Arabia,Al Batin,30000,2000,LB,36,18,...,33,37,45,54,54,10,8,6,13,13
12767,12996,Sun Qibin,26,China PR,Tianjin Quanjian FC,20000,2000,GK,14,7,...,12,30,46,11,10,50,46,51,48,50
12861,13090,Y. Uchimura,33,Japan,Hokkaido Consadole Sapporo,20000,1000,CAM,51,31,...,33,62,45,48,42,13,15,7,15,15
12873,13102,K. Pilkington,44,England,Cambridge United,0,1000,GK,11,12,...,22,56,15,15,13,45,48,44,49,46

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
15,15,P. Dybala,24,Argentina,Juventus,89000000,205000,LF,82,84,...,86,84,23,20,20,5,4,4,5,8
16,16,H. Kane,24,England,Tottenham Hotspur,83500000,205000,ST,75,94,...,90,89,56,36,38,8,10,11,14,11
18,18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK,15,14,...,25,69,25,13,10,87,85,88,85,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,13121,J. Lundstram,19,England,Crewe Alexandra,1100000,1000,CM,34,38,...,43,45,40,48,47,10,13,7,8,9
12893,13122,N. Christoffersson,19,Sweden,Trelleborgs FF,60000,1000,ST,23,52,...,43,42,22,15,19,10,9,9,5,12
12894,13123,B. Worman,16,England,Cambridge United,60000,1000,ST,25,40,...,55,41,32,13,11,6,5,10,6,13
12895,13124,D. Walker-Rice,17,England,Tranmere Rovers,60000,1000,RW,44,50,...,50,46,20,25,27,14,6,14,8,9
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9

In [202]:
import pandas as pd

football = pd.read_csv('./data_sf.csv')

display(
    # Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых выше среднего?
    # Ответ округлите до сотых.
    round(football[football.Wage > football.Wage.mean()].SprintSpeed.mean(), 2),


    # Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых ниже среднего?
    # Ответ округлите до сотых.
    round(football[football.Wage < football.Wage.mean()].SprintSpeed.mean(), 2),


    # Какую позицию (Position) занимает футболист с самой высокой зарплатой (Wage)?
    football[football.Wage == football.Wage.max()].Position[0],


    # Сколько пенальти (Penalties) забили бразильские (Nationality, Brazil)
    # футболисты за период, данные о котором представлены в датасете?
    football[football.Nationality == 'Brazil'].Penalties.sum(),


    # Укажите средний возраст (Age) игроков, у которых точность
    # удара головой (HeadingAccuracy) > 50. Ответ округлите до сотых.
    round(football[football.HeadingAccuracy > 50].Age.mean(), 2),


    # Укажите возраст (Age) самого молодого игрока, у которого хладнокровие
    # (Composure) и реакция (Reactions) превышают 90% от максимального значения,
    # представленного в датасете.
    football[
        (football.Composure > football.Composure.max()*0.9)
        & (football.Reactions > football.Reactions.max()*0.9)
    ].Age.min(),


    # Определите, насколько средняя реакция (Reactions) самых взрослых игроков
    # (т.е. игроков, чей возраст (Age) равен максимальному) больше средней реакции
    # самых молодых игроков. Ответ округлите до сотых.
    round(
        football[
            football.Age == football.Age.max()
        ].Reactions.mean() - football[
            football.Age == football.Age.min()
        ].Reactions.mean(),

        2),


    # Из какой страны (Nationality) происходит больше всего игроков,
    # чья стоимость (Value) превышает среднее значение?
    football[football.Value > football.Value.mean()].Nationality.describe().top,
    #     football[football.Value > football.Value.mean()].Nationality.describe()['top'],
    #     football[football.Value > football.Value.mean()].Nationality.value_counts().index[0],


    # Определите, во сколько раз средняя зарплата (Wage) голкипера (Position, GK)
    # с максимальным значением показателя " Рефлексы" (GKReflexes) выше средней зарплаты
    # голкипера с максимальным значением показателя "Владение мячом" (GKHandling).
    # Ответ округлите до сотых.
    round(
        football[
            (football.Position == 'GK') & (football.GKReflexes == football.GKReflexes.max())
        ].Wage.mean() / football[
            (football.Position == 'GK') & (football.GKHandling == football.GKHandling.max())
        ].Wage.mean(),

        2),

    # Определите, во сколько раз средняя сила удара (ShotPower) самых агрессивных игроков
    # (игроков с максимальным значением показателя "Агрессивность" (Aggression)) выше средней
    # силы удара игроков с минимальной агрессией.
    # Ответ округлите до сотых.
    round(
        football[
            football.Aggression == football.Aggression.max()
        ].ShotPower.mean() / football[
            football.Aggression == football.Aggression.min()
        ].ShotPower.mean(),

        2),
)

67.57

62.41

'RF'

22789

25.59

24

22.64

'Spain'

2.77

2.08